@host=http://localhost:3001

GET {{host}}/api/blogs

###

POST {{host}}/api/blogs
Content-Type: application/json

{
    "title": "Title 4",
    "author": "Author 2",
    "url": "http://www.example.com",
    "likes": 10
}